[project]
name = "Flask-RQ"
version = "0.3.0"
description = "RQ (Redis Queue) integration for Flask and Quart applications."
readme = "README.md"
maintainers = [{ name = "Pallets Ecosystem", email = "contact@palletsprojects.com" }]
license = "MIT"
license-files = ["LICENSE.txt"]
requires-python = ">=3.9"
dependencies = [
    "flask[async]>=3.0",
    "rq>=2.0",
    "typing-extensions>=4.12",
]

[project.optional-dependencies]
quart = [
    "quart>=0.20",
]

[project.urls]
Documentation = "https://flask-rq.readthedocs.io"
Changes = "https://flask-rq.readthedocs.io/en/latest/changes/"
Source = "https://github.com/pallets-eco/flask-rq/"
Chat = "https://discord.gg/pallets"

[build-system]
requires = ["flit-core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "flask_rq"

[dependency-groups]
dev = [
    "ephemeral-port-reserve",
    "mypy",
    "pre-commit",
    "pyright",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "quart",
    "ruff",
    "tox",
    "tox-uv",
]
docs = [
    "furo",
    "myst-parser",
    "quart",
    "sphinx",
]
docs-auto = [
    "sphinx-autobuild",
]
gha-update = [
    "gha-update ; python_version>='3.12'",
]
pre-commit = [
    "pre-commit",
]
tests = [
    "ephemeral-port-reserve",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "quart",
]
typing = [
    "ephemeral-port-reserve",
    "mypy",
    "pyright",
    "pytest",
    "quart",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
    "ignore:CLIENT SETNAME"
]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

[tool.coverage.run]
branch = true
source = ["flask_rq", "tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.report]
exclude_also = [
    "if t.TYPE_CHECKING",
    "raise NotImplementedError",
    ": \\.{3}",
]

[tool.mypy]
python_version = "3.9"
files = ["src", "tests"]
show_error_codes = true
pretty = true
strict = true

[[tool.mypy.overrides]]
module = ["ephemeral_port_reserve"]
ignore_missing_imports = true

[tool.pyright]
pythonVersion = "3.9"
include = ["src", "tests"]
typeCheckingMode = "standard"

[tool.ruff]
src = ["src"]
fix = true
show-fixes = true
output-format = "full"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "I",  # isort
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]

[tool.ruff.lint.isort]
force-single-line = true
order-by-type = false

[tool.gha-update]
tag-only = [
    "slsa-framework/slsa-github-generator",
]

[tool.tox]
env_list = [
    "py3.13", "py3.12", "py3.11", "py3.10", "py3.9",
    "style",
    "typing",
    "docs",
]

[tool.tox.env_run_base]
runner = "uv-venv-lock-runner"
package = "wheel"
wheel_build_env = ".pkg"
constrain_package_deps = true
use_frozen_constraints = true
dependency_groups = ["tests"]
commands = [[
    "pytest", "-v", "--tb=short", "--basetemp={env_tmp_dir}",
    "--cov", "--cov-report=term-missing",
    { replace = "posargs", default = [], extend = true },
]]

[tool.tox.env.style]
dependency_groups = ["pre-commit"]
skip_install = true
commands = [["pre-commit", "run", "--all-files"]]

[tool.tox.env.typing]
dependency_groups = ["typing"]
commands = [
    ["mypy"],
    ["pyright"],
    ["pyright", "--verifytypes", "flask_rq", "--ignoreexternal"],
]

[tool.tox.env.docs]
dependency_groups = ["docs"]
commands = [["sphinx-build", "-E", "-W", "-b", "dirhtml", "docs", "docs/_build/dirhtml"]]

[tool.tox.env.docs-auto]
dependency_groups = ["docs", "docs-auto"]
commands = [["sphinx-autobuild", "-W", "-b", "dirhtml", "--watch", "src", "docs", "docs/_build/dirhtml"]]

[tool.tox.env.update-actions]
labels = ["update"]
dependency_groups = ["gha-update"]
skip_install = true
commands = [["gha-update"]]

[tool.tox.env.update-pre_commit]
labels = ["update"]
dependency_groups = ["pre-commit"]
skip_install = true
commands = [["pre-commit", "autoupdate", "--freeze", "-j4"]]

[tool.tox.env.update-requirements]
labels = ["update"]
skip_install = true
commands = [["uv", "lock", { replace = "posargs", default = ["-U"], extend = true }]]
